server:
  port: 8080
spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    group-id: payment-service
    topics:
      payment: payment

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:2700/commerce?useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta